services:
  - type: web
    name: blaze-cartz
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 120
    healthCheckPath: /health
    plan: free
