create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price numeric(12,2) not null default 0,
  category text default 'General',
  image_url text default '',
  stock integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  city text not null,
  state text not null,
  pincode text not null,
  payment_method text not null default 'COD',
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12,2) not null default 0,
  status text not null default 'New',
  created_at timestamptz not null default now()
);

insert into public.products (name, description, price, category, image_url, stock)
values
('Classic Blaze Tee', 'Premium everyday cotton tee with a clean Blaze_cartz mark.', 499, 'Fashion', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80', 25),
('Urban Essential Hoodie', 'Soft heavyweight hoodie designed for a minimal streetwear look.', 999, 'Fashion', 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80', 15),
('Everyday Carry Backpack', 'Clean, practical backpack for college, work and daily travel.', 799, 'Bags', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80', 18)
where not exists (select 1 from public.products);
